version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nir
      MONGO_INITDB_ROOT_PASSWORD: nir
      MONGO_INITDB_DATABASE: mydb

    volumes:
      - db:/data/db
    ports:
      - "27017:27017"
  
  server:
    image: nest-server
    build: 
      dockerfile: ./server.Dockerfile
    depends_on:
      - mongo
    environment:
      - DATABASE_URI=mongodb://mongo:27017
      - DB_NAME=mydb
      - DB_USERNAME=nir
      - DB_PASSWORD=nir
    ports:
      - "3333:3333"

  client:
    image: react-app
    build: 
      dockerfile: ./client.Dockerfile
    environment:
      - NX_API_BASE_URL=http://localhost:3333
    ports:
      - "4200:4200"

volumes:
  db: